### PR TITLE
$mdColorPicker: adds skipHide and preserveScope to options

### LINKED ISSUE #47: $mdColorPicker: support options to keep the colorpicker from closing an open dialog
setting `preserveScope` and `skipHide` to true while opening the color picker from an open mdDialog will keep the dialog component open for a user to select a color, and return to the original dialog

### PR DESCRIPTION
**Pull request by dgavigan**
closes #47

### CODE REVIEW

**Comment by brianpkelley** [comment]
Do you think there is a valid reason to include these in the directives options instead of just always setting them on the dialog?

**Comment by dgavigan** [comment]
I had started to originally just set them as you described. I've tested in my application and everything works as expected even without emitting from an active open dialog. 

However I kept them as options just in case there were adverse effects in further ngMaterial updates, or from someone's application that they could opt in or out of these settings.

Perhaps $mdColorPicker could detect if there is an open dialog and apply these settings internally? This could eliminate the need from having to set them in the directive, as well as having unnecessary options enabled when not needed

**Comment by brianpkelley** [comment]
Thanks for your help and input.  

I'm only rejecting this pull request so the changes can be made on the /feature/v0.2.5 branch instead.  It's probably possible to set which branch to merge PRs into, but I'm still pretty new at managing a repo.

**Comment by dgavigan** [comment]
no worries @brianpkelley 

ill see if i cant refine it a bit more as discussed, and re do the PR for your feature branch

**Pull request closed without merging**
